# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  binary: metal
  ldflags:
   - -X github.com/equinix/metal-cli/cmd.Version={{.Version}}
   - -X github.com/equinix/metal-cli/cmd.Build=${.Commit}"

  goos:
    - freebsd
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: arm64
    - goos: darwin
      goarch: arm
archives:
- format: binary
  name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
